### ISSUE TITLE
老哥你活了？

### ISSUE THREAD

**Issue by SekiBetu** [jh10001/ONScripter-Jh#1]
可以适配下安卓12吗，虽然目前运行着没啥大问题
https://onscripter.osdn.jp/onscripter_devel.2022.html
这个老哥也还在坚持更新，上个月支持了安卓11了，只不过他的版本不支持中文编码

**Comment by jh10001** [comment]
[onscripter-jh-v0.8.0.arm64.apk.zip](https://github.com/jh10001/ONScripter-Jh/files/9291853/onscripter-jh-v0.8.0.arm64.apk.zip)

**Comment by jh10001** [comment]
[https://github.com/jh10001/ONScripter-Jh/releases](https://github.com/jh10001/ONScripter-Jh/releases)

**Comment by KoiYuri** [comment]
请问大佬您还在吗？请问有iOS版本吗？呜呜呜现在

**Comment by KoiYuri** [comment]
> 请问大佬你还在吗？请问有iOS版本吗？呜呜呜呜现在

**Comment by KoiYuri** [comment]
> https://github.com/jh10001/ONScripter-Jh/releases
